### ISSUE TITLE
'FileNotFoundError' even if my txt file and the python file are in the same catalog

### ISSUE THREAD

**Issue by The-chosen** [techstay/run-python-simply#3]
```
Traceback (most recent call last):
  File "C:\Users\YY\Desktop\361.py", line 1, in <module>
    outfile = open('w.txt', 'r')
FileNotFoundError: [Errno 2] No such file or directory: 'w.txt'
```
When I use the atom-runner, I can open the file.
When I use IDLE　to run my code, it can open the file,too.
Thus , I think this may be an issue.

**Comment by techstay** [comment]
Thanks for submitting issues. I will fix it later.

**Comment by techstay** [comment]
It should be fixed now. Have a try and tell me  is it work.

**Comment by The-chosen** [comment]
Now I cannot even open the cmd after I press F5. My computer's system is windows. I'm afraid that there's still something wrong.

**Comment by techstay** [comment]
This time you may need to config it manully to set the conmmand in the settings. The command is in the [RADME](https://github.com/techstay/run-python-simply#config). Maybe I should add an autoconfigurer to detect and set the proper command settings
